step 15: refs to externally defined identifiers typically ask for trouble
In our case, `Optional.ensuringNotNull` is unsafe, because it can be hijacked
by specially crafted code.

    val Optional = "uh-oh"
    println(new Optional(null).getOrElse(null))

    [error] /Users/xeno_by/Projects/macrology201/core/src/main/scala/Test.scala:6: value ensuringNotNull is not a member of String
    [error]     println(new Optional(null).getOrElse(null))
    [error]                                         ^
    [error] one error found

Even such common names as Some and None are not safe.
One might think "who in their right mind would name their variables/classes
using common names?!", but that definitely happens :)